twig:
    paths: ['%kernel.project_dir%/templates']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['bootstrap_4_layout.html.twig']
    globals:
        srv: '@App\Service\TwigService'
#        srv.user: '@App\Service\UserDataService'
#        srv.filter: '@App\Service\FilterService'
#        srv.comment: '@App\Service\CommentService'
